/**
 * Tune Moon — sound system.
 *
 * Moon is the last Tune, and the one people speak. It has 27 sounds.
 *
 *   vowels          i e a o u
 *   nasals          m n q
 *   voiced stops    b d g
 *   voiceless stops p t k
 *   breath          h
 *   alveolar rub    s z
 *   labial rub      f v
 *   palatal rub     x j
 *   dental rub      c C
 *   glides          w l r y
 *
 * Moon is Rock spoken quickly. The stress settled on the first
 * syllable, unstressed vowels dropped out, and the consonants that
 * ended up beside each other stayed there. That is where every cluster
 * comes from, and it is why Moon is short.
 *
 *   Rock  bat.mis   ->   Moon  batmis, batmis -> batmis
 *   Rock  bat.mis   ->   Moon  batms  -> batms, then batems
 *
 * Eight shapes survived:
 *
 *   one syllable    CVC   CVCC   CCVC   CCVCC
 *   two syllables   CVCVC   CVCCVC   CCVCVC   CVCVCC
 *
 * Moon is hand tuned. Rock is generated by rule and Tree is generated
 * by rule, but Moon is a lexicon people built, and it is kept in
 * `tune.csv` at the root of the package. This module says what Moon's
 * shapes are so that lexicon can be checked against them.
 */

// ─── Inventory ──────────────────────────────────────────

export const VOWELS = ['i', 'e', 'a', 'o', 'u']

export const NASALS = ['m', 'n', 'q']
export const VOICED_STOPS = ['b', 'd', 'g']
export const VOICELESS_STOPS = ['p', 't', 'k']
export const BREATH = ['h']
export const ALVEOLAR_RUB = ['s', 'z']
export const LABIAL_RUB = ['f', 'v']
export const PALATAL_RUB = ['x', 'j']
export const DENTAL_RUB = ['c', 'C']
export const GLIDES = ['w', 'l', 'r', 'y']

export const CONSONANTS = [
  ...NASALS,
  ...VOICED_STOPS,
  ...VOICELESS_STOPS,
  ...BREATH,
  ...ALVEOLAR_RUB,
  ...LABIAL_RUB,
  ...PALATAL_RUB,
  ...DENTAL_RUB,
  ...GLIDES,
]

export const SOUNDS = [...VOWELS, ...CONSONANTS]

export const RUBS = [
  ...ALVEOLAR_RUB,
  ...LABIAL_RUB,
  ...PALATAL_RUB,
  ...DENTAL_RUB,
]

// ─── Roles ──────────────────────────────────────────────

/**
 * Moon has five roles. Rock had three. The two extra ones came from
 * the two Rock vowels that split.
 *
 *   Rock -i action   ->   Moon -i action, -e relation
 *   Rock -u feature  ->   Moon -u feature, -o operator
 *
 * The bare root works as a modifier, which is the feature form worn
 * down one step further because a modifier is never stressed.
 */
export const ROLES: Array<{ name: string; vowel: string; note: string }> = [
  { name: 'entity', vowel: 'a', note: 'what exists' },
  { name: 'action', vowel: 'i', note: 'what happens' },
  { name: 'feature', vowel: 'u', note: 'what something is like' },
  { name: 'relation', vowel: 'e', note: 'how things connect' },
  { name: 'operator', vowel: 'o', note: 'how meaning is controlled' },
]

// ─── Shapes ─────────────────────────────────────────────

/**
 * The eight shapes Moon allows. Stress falls on the first syllable of
 * every one of them.
 */
export const SHAPES = [
  'CVC',
  'CVCC',
  'CCVC',
  'CCVCC',
  'CVCVC',
  'CVCVCVC',
]

/**
 * The six letter shapes are gone.
 *
 * `CVCCVC` is exactly `CVC` followed by `CVC`, and a join only carries
 * a linker when the two consonants meeting would run together, so a
 * word of that shape cannot be told from two words of three letters
 * each. `CCVCVC` and `CVCVCC` went with it.
 *
 * With those three out, no atom shape equals a join of two atoms, at
 * any length.
 */
export const DROPPED_SHAPES = ['CVCCVC', 'CCVCVC', 'CVCVCC']

export const SHAPE_SET = new Set(SHAPES)

// ─── Sort Order ─────────────────────────────────────────

export const CHAR_ORDER =
  'i e a o u m n q b d g p t k h s z f v x j c C w l r y'.split(' ')

export const CHAR_RANK = new Map(CHAR_ORDER.map((c, i) => [c, i]))

export function compareWords(a: string, b: string): number {
  const len = Math.max(a.length, b.length)
  for (let i = 0; i < len; i++) {
    const ra = CHAR_RANK.get(a[i]) ?? 99
    const rb = CHAR_RANK.get(b[i]) ?? 99
    if (ra !== rb) {
      return ra - rb
    }
  }
  return 0
}

// ─── Shape ──────────────────────────────────────────────

export function isVowel(ch: string): boolean {
  return VOWELS.includes(ch)
}

export function isConsonant(ch: string): boolean {
  return CONSONANTS.includes(ch)
}

/** `bat` becomes `CVC`, `stulatx` becomes `CCVCVCC`. */
export function toShape(word: string): string | null {
  let shape = ''
  for (const sound of word) {
    if (isVowel(sound)) {
      shape += 'V'
    } else if (isConsonant(sound)) {
      shape += 'C'
    } else {
      return null
    }
  }
  return shape
}

export function countSyllables(shape: string): number {
  return [...shape].filter(s => s === 'V').length
}

export function isMoonShape(word: string): boolean {
  const shape = toShape(word)
  return shape !== null && SHAPE_SET.has(shape)
}

// ─── Clusters ───────────────────────────────────────────

/**
 * The consonant pairs Moon lets meet.
 *
 * These began in `4.ts`, written down while the four letter words were
 * being built. The lexicon has grown past that list since, so what is
 * here is the two put together: every pair `4.ts` allowed, plus every
 * pair `tune.csv` actually uses.
 *
 * `4.ts` also refused any cluster holding `x` or `j`, which would rule
 * out `dj` and `tx`. Those two are the most common clusters in the
 * language by a wide margin, and they are digraphs for single sounds
 * rather than clusters at all, which is why they were being handled
 * separately. They are allowed here.
 *
 * `tk` is left out. It occurs four times and all four are the same
 * word, `tkslit`, which opens on four consonants and is not a Moon
 * shape to begin with.
 */
export const ONSET_CLUSTERS = new Set(
  'bl br cr dj dr fl fr gl gr kl kr pl pr tr tx vr'.split(' '),
)

export const CODA_CLUSTERS = new Set(
  (
    'dj ft kx lb ld lf lk lp lt lv lx mp nd nk nt qk rb rd rf rg rk rm ' +
    'rn rp rt rv rx sk sp st tx xt'
  ).split(' '),
)

/** Two letters standing for one sound, so they count as neither cluster. */
export const AFFRICATES = ['dj', 'tx', 'ts', 'dz']

/**
 * The consonants that mark a join between two words.
 *
 * A join takes a sibilant matching the voice of the consonant before
 * it, `z` after a voiced one and `s` after a voiceless one. When the
 * two consonants meeting are the same, or differ only by voice, a
 * sibilant does not pull them apart and `l` stands in.
 *
 *   man + man  ->  manzman        dag + man  ->  dagzman
 *   mat + man  ->  matsman        s + s      ->  sls
 *
 * For that to be readable, a linker in the middle of three consonants
 * has to be a linker and nothing else. So no word may end on a
 * consonant plus a linker, and none may begin on a linker plus a
 * consonant.
 *
 *   end     Cl  Cs  Cz
 *   start   lC  sC  zC
 *
 * The lists below are filtered by that rather than written out, so
 * changing a linker re-answers which clusters survive.
 */
export const LINKERS = ['l', 's', 'z']

export const VOICED = 'mnqgdbvzjCwlry'.split('')
export const VOICELESS = 'ptkhsfxc'.split('')

/** The seven pairs that differ by voice and nothing else. */
export const VOICE_PAIRS = ['pb', 'dt', 'gk', 'sz', 'fv', 'cC', 'xj']

const voicePaired = new Set<string>()
for (const pair of VOICE_PAIRS) {
  voicePaired.add(pair)
  voicePaired.add(pair[1] + pair[0])
}

/**
 * A join only needs help when the two consonants are the same, or when
 * they differ by voice and nothing else. Anything else is already far
 * enough apart and the words run straight together.
 */
export function needsLinker(a: string, b: string): boolean {
  return a === b || voicePaired.has(a + b)
}

/**
 * The linker is a sibilant matching the voice of the consonant before
 * it. When that sibilant is already one of the two it would vanish
 * into them, and `l` stands in.
 */
export function linkerFor(a: string, b: string): string {
  const sibilant = VOICED.includes(a) ? 'z' : 's'
  return a === sibilant || b === sibilant ? 'l' : sibilant
}

/** Two words joined, with a linker only where one is needed. */
export function joinWords(first: string, second: string): string {
  const a = first[first.length - 1]
  const b = second[0]
  return needsLinker(a, b) ? first + linkerFor(a, b) + second : first + second
}

function withoutLinkers(
  clusters: Set<string>,
  at: 0 | 1,
): Set<string> {
  return new Set([...clusters].filter(c => !LINKERS.includes(c[at])))
}

/** What is left once the linkers are protected. */
export const ONSET_CLUSTERS_CLEAR = withoutLinkers(ONSET_CLUSTERS, 0)
export const CODA_CLUSTERS_CLEAR = withoutLinkers(CODA_CLUSTERS, 1)

export function testOnsetCluster(cluster: string): boolean {
  return ONSET_CLUSTERS_CLEAR.has(cluster)
}

export function testCodaCluster(cluster: string): boolean {
  return CODA_CLUSTERS_CLEAR.has(cluster)
}

// ─── Confusable Sounds ──────────────────────────────────

/**
 * Sounds close enough that swapping one for the other does not make a
 * new word. Also from `4.ts`, and they line up with the numbers in
 * `code/similarity.ts`: everything grouped here scores high in
 * `ONSET_SIMILARITY` and `CODA_SIMILARITY`.
 */
export const SIMILAR_GROUPS: Array<Array<string>> = [
  ['m', 'n', 'q'],
  ['b', 'p'],
  ['d', 't'],
  ['b', 'd'],
  ['p', 't'],
  ['g', 'k'],
  ['s', 'z'],
  ['x', 'j'],
  ['c', 'C'],
  ['f', 'v'],
  ['s', 'c'],
  ['z', 'C'],
  ['j', 'C'],
  ['x', 'c'],
  ['f', 'c'],
  ['C', 'v'],
  ['l', 'r'],
]

/**
 * Vowels that sit next to each other on the ladder `i e a o u`. The
 * same four steps `VOWEL_PAIRS` in `code/similarity.ts` scores at 4
 * and 5, its two shortest distances.
 */
export const ADJACENT_VOWELS = new Set(
  'ie ei ea ae ao oa ou uo'.split(' '),
)

const similarTo = new Map<string, Set<string>>()
for (const sound of CONSONANTS) {
  similarTo.set(sound, new Set([sound]))
}
for (const group of SIMILAR_GROUPS) {
  for (const a of group) {
    for (const b of group) {
      similarTo.get(a)?.add(b)
    }
  }
}

export function areSimilar(a: string, b: string): boolean {
  return similarTo.get(a)?.has(b) ?? false
}

export function vowelsClose(a: string, b: string): boolean {
  return a === b || ADJACENT_VOWELS.has(a + b)
}

/**
 * Two words too close to be two words.
 *
 * `star` and `stal` differ by one liquid and say nothing different, so
 * one of them has to go. `star` and `stap` differ by more than a pair
 * and are fine.
 *
 * Every consonant has to be similar and the vowel has to be close
 * before this fires, so it only catches words that are near copies all
 * the way through.
 */
export function tooClose(a: string, b: string): boolean {
  if (a.length !== b.length) {
    return false
  }
  const shapeA = toShape(a)
  const shapeB = toShape(b)
  if (!shapeA || !shapeB || shapeA !== shapeB) {
    return false
  }
  for (let i = 0; i < a.length; i++) {
    const same =
      shapeA[i] === 'V' ? vowelsClose(a[i], b[i]) : areSimilar(a[i], b[i])
    if (!same) {
      return false
    }
  }
  return a !== b
}

// ─── Syllable Rules ─────────────────────────────────────

/**
 * Rhymes Moon will not say. A close front vowel followed by a liquid
 * blurs into the liquid, so `bil` and `ber` are not words Moon can
 * hold apart from `bi` and `be`.
 */
export const BAD_RHYME = ['il', 'el', 'ir', 'er']

/** Sounds too weak to close a syllable. They need a vowel after them. */
export const BAD_CLOSE = ['y', 'h', 'w']

/** Sounds that cannot open a syllable. */
export const BAD_OPEN = ['q']

export type SyllableRule = {
  name: string
  note: string
  test: (syllable: string) => boolean
}

export const SYLLABLE_RULES: Array<SyllableRule> = [
  {
    name: 'no-weak-close',
    note: 'a syllable never ends in y, h or w',
    test: syllable => !BAD_CLOSE.includes(syllable[syllable.length - 1]),
  },
  {
    name: 'no-back-open',
    note: 'a syllable never starts with q',
    test: syllable => !BAD_OPEN.includes(syllable[0]),
  },
  {
    name: 'no-blurred-rhyme',
    note: 'a syllable never ends in il, el, ir or er',
    test: syllable => !BAD_RHYME.includes(syllable.slice(-2)),
  },
]

export function testSyllable(syllable: string): {
  ok: boolean
  broke: Array<string>
} {
  const broke = SYLLABLE_RULES.filter(r => !r.test(syllable)).map(r => r.name)
  return { ok: broke.length === 0, broke }
}

/** Runs the syllable rules over every syllable of a word. */
export function testSounding(word: string): {
  ok: boolean
  broke: Array<string>
} {
  const broke = new Set<string>()
  for (const syllable of toSyllables(word)) {
    for (const name of testSyllable(syllable).broke) {
      broke.add(name)
    }
  }
  return { ok: broke.size === 0, broke: [...broke] }
}

/** Where a word breaks into syllables, with the stress on the first. */
export function toSyllables(word: string): Array<string> {
  const shape = toShape(word)
  if (!shape) {
    return [word]
  }
  /** A cluster in the middle splits down the middle, so `batmis` is
   * `bat` and `mis`, not `ba` and `tmis`. */
  const parts: Array<string> = []
  let current = ''
  let seenVowel = false
  for (let i = 0; i < word.length; i++) {
    const sound = word[i]
    if (isVowel(sound)) {
      if (seenVowel) {
        parts.push(current.slice(0, -1))
        current = current.slice(-1)
      }
      seenVowel = true
    }
    current += sound
  }
  parts.push(current)
  return parts.filter(p => p.length > 0)
}
